export const GET_ERRORS = "GET_ERRORS";
export const GOLFER_LOADING = "GOLFER_LOADING";
export const SET_CURRENT_GOLFER = "SET_CURRENT_GOLFER";
export const UPDATE_DIFFERENTIAL = "UPDATE_DIFFERENTIAL";
export const UPDATE_HANDICAP = "UPDATE_HANDICAP";
